FROM openjdk:11
ARG JAR_FILE
ENV BOOKS_ENVIRONMENT=$BOOKS_ENVIRONMENT
ENV MYSQL_USERNAME=$MYSQL_USERNAME
ENV MYSQL_PASSWORD=$MYSQL_PASSWORD
ENV MYSQL_HOST=$MYSQL_HOST
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java", "-jar", "/app.jar"]