apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      bookstore: web
  template:
    metadata:
      labels:
        bookstore: web
    spec:
      containers:
        - name: bookstore
          image: "jordanthomas761/book-store:0.0.2"
---
apiVersion: v1
kind: Service
metadata:
  name: bookstore-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    bookstore: web
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001